// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rsAPI.Data;

#nullable disable

namespace rsAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240722121538_deneme")]
    partial class deneme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("rsAPI.Data.Entities.Concrete.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("kategoriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("kategoriler");
                });

            modelBuilder.Entity("rsAPI.Data.Entities.Concrete.daireTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("daireTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("daireTipleri");
                });

            modelBuilder.Entity("rsAPI.Data.Entities.Concrete.ilanlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ilanAciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ilanBaslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ilanDaireTipiId")
                        .HasColumnType("int");

                    b.Property<string>("ilanFiyat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ilanKategorisiId")
                        .HasColumnType("int");

                    b.Property<int>("ilanKisi")
                        .HasColumnType("int");

                    b.Property<string>("ilanResmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ilanDaireTipiId");

                    b.HasIndex("ilanKategorisiId");

                    b.ToTable("ilanlar");
                });

            modelBuilder.Entity("rsAPI.Data.Entities.Concrete.ilanlar", b =>
                {
                    b.HasOne("rsAPI.Data.Entities.Concrete.daireTip", "ilanDaireTipi")
                        .WithMany()
                        .HasForeignKey("ilanDaireTipiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rsAPI.Data.Entities.Concrete.Kategori", "ilanKategorisi")
                        .WithMany()
                        .HasForeignKey("ilanKategorisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ilanDaireTipi");

                    b.Navigation("ilanKategorisi");
                });
#pragma warning restore 612, 618
        }
    }
}
